import React from 'react'

function VLYMM(props) {
  return (
    <div className="form vehicleLookupDiv">
      <div className="vehicleLookupInput">
        <label htmlFor="lookupYear">Year</label>
        <select name="lookupYear">
            <option value="1900">1900</option>
            <option value="1901">1901</option>
            <option value="1902">1902</option>
            <option value="1903">1903</option>
            <option value="1904">1904</option>
            <option value="1905">1905</option>
            <option value="1906">1906</option>
            <option value="1907">1907</option>
            <option value="1908">1908</option>
            <option value="1909">1909</option>
            <option value="1910">1910</option>
            <option value="1911">1911</option>
            <option value="1912">1912</option>
            <option value="1913">1913</option>
            <option value="1914">1914</option>
            <option value="1915">1915</option>
            <option value="1916">1916</option>
            <option value="1917">1917</option>
            <option value="1918">1918</option>
            <option value="1919">1919</option>
            <option value="1920">1920</option>
            <option value="1921">1921</option>
            <option value="1922">1922</option>
            <option value="1923">1923</option>
            <option value="1924">1924</option>
            <option value="1925">1925</option>
            <option value="1926">1926</option>
            <option value="1927">1927</option>
            <option value="1928">1928</option>
            <option value="1929">1929</option>
            <option value="1930">1930</option>
            <option value="1931">1931</option>
            <option value="1932">1932</option>
            <option value="1933">1933</option>
            <option value="1934">1934</option>
            <option value="1935">1935</option>
            <option value="1936">1936</option>
            <option value="1937">1937</option>
            <option value="1938">1938</option>
            <option value="1939">1939</option>
            <option value="1940">1940</option>
            <option value="1941">1941</option>
            <option value="1942">1942</option>
            <option value="1943">1943</option>
            <option value="1944">1944</option>
            <option value="1945">1945</option>
            <option value="1946">1946</option>
            <option value="1947">1947</option>
            <option value="1948">1948</option>
            <option value="1949">1949</option>
            <option value="1950">1950</option>
            <option value="1951">1951</option>
            <option value="1952">1952</option>
            <option value="1953">1953</option>
            <option value="1954">1954</option>
            <option value="1955">1955</option>
            <option value="1956">1956</option>
            <option value="1957">1957</option>
            <option value="1958">1958</option>
            <option value="1959">1959</option>
            <option value="1960">1960</option>
            <option value="1961">1961</option>
            <option value="1962">1962</option>
            <option value="1963">1963</option>
            <option value="1964">1964</option>
            <option value="1965">1965</option>
            <option value="1966">1966</option>
            <option value="1967">1967</option>
            <option value="1968">1968</option>
            <option value="1969">1969</option>
            <option value="1970">1970</option>
            <option value="1971">1971</option>
            <option value="1972">1972</option>
            <option value="1973">1973</option>
            <option value="1974">1974</option>
            <option value="1975">1975</option>
            <option value="1976">1976</option>
            <option value="1977">1977</option>
            <option value="1978">1978</option>
            <option value="1979">1979</option>
            <option value="1980">1980</option>
            <option value="1981">1981</option>
            <option value="1982">1982</option>
            <option value="1983">1983</option>
            <option value="1984">1984</option>
            <option value="1985">1985</option>
            <option value="1986">1986</option>
            <option value="1987">1987</option>
            <option value="1988">1988</option>
            <option value="1989">1989</option>
            <option value="1990">1990</option>
            <option value="1991">1991</option>
            <option value="1992">1992</option>
            <option value="1993">1993</option>
            <option value="1994">1994</option>
            <option value="1995">1995</option>
            <option value="1996">1996</option>
            <option value="1997">1997</option>
            <option value="1998">1998</option>
            <option value="1999">1999</option>
            <option value="2000">2000</option>
            <option value="2001">2001</option>
            <option value="2002">2002</option>
            <option value="2003">2003</option>
            <option value="2004">2004</option>
            <option value="2005">2005</option>
            <option value="2006">2006</option>
            <option value="2007">2007</option>
            <option value="2008">2008</option>
            <option value="2009">2009</option>
            <option value="2010">2010</option>
            <option value="2011">2011</option>
            <option value="2012">2012</option>
            <option value="2013">2013</option>
            <option value="2014">2014</option>
            <option value="2015">2015</option>
            <option value="2016">2016</option>
            <option value="2017">2017</option>
            <option value="2018">2018</option>
            <option value="2019">2019</option>
            <option value="2020" selected="selected">2020</option>
          </select>
          <label htmlFor="lookupMake">Make</label>
          <select name="lookupMake">
            <option value="" selected="selected" disabled="disabled">Select a manufacturer...</option>
            <option value="ACG">ACG</option>
            <option value="Aston">Aston Martin</option>
            <option value="Auto">Auto Alliance</option>
            <option value="Blue">Blue Diamond</option>
            <option value="BMW">BMW</option>
            <option value="Buell">Buell</option>
            <option value="Bugatti">Bugatti</option>
            <option value="Chevrolet">Chevrolet</option>
            <option value="Chrysler">Chrysler</option>
            <option value="Club">Club Car</option>
            <option value="Coachworks">Coachworks</option>
            <option value="Cooper">Cooper Cycles</option>
            <option value="Daimler">Daimler</option>
            <option value="E-One">E-One</option>
            <option value="Fiat">Fiat</option>
            <option value="Ford">Ford</option>
            <option value="GM">GM</option>
            <option value="Hino">Hino</option>
            <option value="Hombilt">Hombilt</option>
            <option value="Honda">Honda</option>
            <option value="Hyundia">Hyundia</option>
            <option value="International">International</option>
            <option value="Jaguar">Jaguar</option>
            <option value="Jialing">Jialing</option>
            <option value="Kenworth">Kenworth</option>
            <option value="Kia">Kia</option>
            <option value="Lamborghini">Lamborghini</option>
            <option value="Land">Land Rover</option>
            <option value="Latitude">Latitude</option>
            <option value="Lotus">Lotus</option>
            <option value="Mack">Mack Truck</option>
            <option value="Maserati">Maserati</option>
            <option value="Mazda">Mazda</option>
            <option value="Mercedes-Benz">Mercedes-Benz</option>
            <option value="Mills">Mills Manufacturing</option>
            <option value="Mitsubishi">Mitsubishi</option>
            <option value="Motorcycle">Motorcycle Machine Shop Services</option>
            <option value="NABI">NABI</option>
            <option value="Navistar">Navistar</option>
            <option value="Nissan">Nissan</option>
            <option value="NUMMI">NUMMI</option>
            <option value="Optima">Optima</option>
            <option value="Oshkosh">Oshkosh</option>
            <option value="Owosso">Owosso</option>
            <option value="PACCAR">PACCAR</option>
            <option value="Peterbilt">Peterbilt</option>
            <option value="Quest">Quest Manufacturing</option>
            <option value="Renault">Renault</option>
            <option value="Rolls">Rolls Royce</option>
            <option value="Subaru">Subaru</option>
            <option value="Suzuki">Suzuki</option>
            <option value="Tesla">Tesla</option>
            <option value="TMMBC">TMMBC</option>
            <option value="Toyota">Toyota</option>
            <option value="UD">UD</option>
            <option value="Volkswagen">Volkswagen</option>
            <option value="Volvo">Volvo</option>
            <option value="Westward">Westward</option>
            <option value="Workhorse">Workhorse</option>
          </select>
          <label htmlFor="lookupModel">Model</label>
          <select name="lookupModel">
            <option value="First select a make..." selected="selected" disabled="disabled">First select a manufacturer...</option>
          </select>
      </div>
      <button className="button hidden" id="confirmLookupResults">Vehicle Info Is Correct</button>
  </div>
  )
}

export default VLYMM